version: "3.8"

services:
  conduit:
    image: matrixconduit/matrix-conduit:latest
    environment:
      - CONDUIT_SERVER_NAME=matrix.fferrando.cc
      - CONDUIT_DATABASE_BACKEND=rocksdb
      - CONDUIT_ALLOW_REGISTRATION=false
      - CONDUIT_ALLOW_FEDERATION=true
      - CONDUIT_PORT=6167
      - CONDUIT_ADDRESS=0.0.0.0
      - CONDUIT_LOG=info
      - CONDUIT_CONFIG=""
      - CONDUIT_DATABASE_PATH=/var/lib/matrix-conduit
    volumes:
      - /opt/swarm_config/conduit/conduit:/var/lib/matrix-conduit
    networks:
      - traefik-net
      - matrix-internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.conduit.entrypoints=cf-public"
        - "traefik.http.routers.conduit.rule=Host(`matrix.fferrando.cc`)"
        - "traefik.http.services.conduit.loadbalancer.server.port=6167"

  tg-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=mautrix
      - POSTGRES_PASSWORD=mautrix
    volumes:
      - /opt/swarm_config/conduit/tg-db:/var/lib/postgresql/data
    networks:
      - matrix-internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 1G
          cpus: "1.0"

  wa-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=mautrix
      - POSTGRES_PASSWORD=mautrix
    volumes:
      - /opt/swarm_config/conduit/wa-db:/var/lib/postgresql/data
    networks:
      - matrix-internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 1G
          cpus: "1.0"

  mautrix-whatsapp:
    image: dock.mau.dev/mautrix/whatsapp:latest
    volumes:
      - /opt/swarm_config/conduit/whatsapp:/data
    networks:
      - matrix-internal
    depends_on:
      - wa-db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  mautrix-telegram:
    image: dock.mau.dev/mautrix/telegram:latest
    volumes:
      - /opt/swarm_config/conduit/telegram:/data
    networks:
      - matrix-internal
    depends_on:
      - tg-db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  traefik-net:
    external: true
  matrix-internal:
    driver: overlay
