[compute]
balthazar.rdfilippo.homelab ansible_host=192.168.10.102 ansible_user=balthazar node_labels='{"role": "compute", "zone": "swarm"}'
caelium.rdfilippo.homelab   ansible_host=192.168.10.103 ansible_user=caelium   node_labels='{"role": "compute", "zone": "swarm"}'

[storage]
casper.rdfilippo.homelab    ansible_host=192.168.10.101 ansible_user=casper    node_labels='{"role": "storage", "zone": "swarm"}'

[network]
magi.rdfilippo.homelab      ansible_host=192.168.10.100 ansible_user=magi      node_labels='{"role": "network", "zone": "vault"}'

[managers]
magi.rdfilippo.homelab
balthazar.rdfilippo.homelab
casper.rdfilippo.homelab

[workers]
caelium.rdfilippo.homelab

[swarm:children]
managers
workers

[cluster:children]
compute
storage
